---
title: "Energy Consumption Characteristic Trends of General Library"
author: "Tony Yen"
date: "2017年1月30日"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: spacelab
  
---
```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
#setwd("D:/R/Web")
library(datasets)
#generalLibrary=read.table("generalLibrary.csv",header=TRUE,sep=",")
generalLibrary=read.table("https://raw.githubusercontent.com/yenishrepublic/energysaving_ntu/master/generalLibrary.csv", header=TRUE,sep=",")
generalLibrarybase=read.table("https://raw.githubusercontent.com/yenishrepublic/energysaving_ntu/master/generalLibrarybase.csv", header=TRUE,sep=",")
# data(generalLibrary)
```

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(plotly)
library(dygraphs)
library(xts)
library(knitr)
```

Weekday Average Trends
=====================================

###
###
### Weekday Average Trends

Row {.tabset}
-----------------------------------------------------------------------

### May

```{r}

trace_1 <- round(generalLibrary$mean.weekday.may.1,1)
trace_2 <- round(generalLibrary$mean.weekday.may.2,1)
trace_3 <- round(generalLibrary$mean.weekday.may.3,1)
x <- generalLibrary$hr

plot<-plot_ly(x = ~x, y = ~trace_1, name = 'Weekdays 2014', type = 'scatter', mode = 'lines+markers') %>%
  add_trace(y = ~trace_2, name = 'Weekdays 2015', mode = 'lines+markers') %>%
  add_trace(y = ~trace_3, name = 'Weekdays 2016', mode = 'lines+markers')%>%
  layout(                       
         xaxis = list(           
            title = "Time (Hours)",      
            showgrid = F),       
         yaxis = list(           
            title = "Average Energy Consumption (kWh per Hour)",
            range=c(0,1500)),
         legend = list(
           orientation="h"
         )
  )

plot

```

### July

```{r}

trace_1 <- round(generalLibrary$mean.weekday.jul.1,1)
trace_2 <- round(generalLibrary$mean.weekday.jul.2,1)
trace_3 <- round(generalLibrary$mean.weekday.jul.3,1)
x <- generalLibrary$hr

plot<-plot_ly(x = ~x, y = ~trace_1, name = 'Weekdays 2014', type = 'scatter', mode = 'lines+markers') %>%
  add_trace(y = ~trace_2, name = 'Weekdays 2015', mode = 'lines+markers') %>%
  add_trace(y = ~trace_3, name = 'Weekdays 2016', mode = 'lines+markers')%>%
  layout(                       
         xaxis = list(           
            title = "Time (Hours)",      
            showgrid = F),       
         yaxis = list(           
            title = "Average Energy Consumption (kWh per Hour)",
            range=c(0,1500)),
         legend= list(
           orientation="h"
         )
  )

plot

```

### September

```{r}

trace_1 <- round(generalLibrary$mean.weekday.sep.1,1)
trace_2 <- round(generalLibrary$mean.weekday.sep.2,1)
trace_3 <- round(generalLibrary$mean.weekday.sep.3,1)
x <- generalLibrary$hr

plot<-plot_ly(x = ~x, y = ~trace_1, name = 'Weekdays 2014', type = 'scatter', mode = 'lines+markers') %>%
  add_trace(y = ~trace_2, name = 'Weekdays 2015', mode = 'lines+markers') %>%
  add_trace(y = ~trace_3, name = 'Weekdays 2016', mode = 'lines+markers')%>%
  layout(                       
         xaxis = list(           
            title = "Time (Hours)",      
            showgrid = F),       
         yaxis = list(           
            title = "Average Energy Consumption (kWh per Hour)",
            range=c(0,1500)),
         legend= list(
           orientation="h"
         )
  )

plot

```

### December

```{r}

trace_1 <- round(generalLibrary$mean.weekday.dec.1,1)
trace_2 <- round(generalLibrary$mean.weekday.dec.2,1)
trace_3 <- round(generalLibrary$mean.weekday.dec.3,1)
x <- generalLibrary$hr

plot<-plot_ly(x = ~x, y = ~trace_1, name = 'Weekdays 2014', type = 'scatter', mode = 'lines+markers') %>%
  add_trace(y = ~trace_2, name = 'Weekdays 2015', mode = 'lines+markers') %>%
  add_trace(y = ~trace_3, name = 'Weekdays 2016', mode = 'lines+markers')%>%
  layout(                       
         xaxis = list(           
            title = "Time (Hours)",      
            showgrid = F),       
         yaxis = list(           
            title = "Average Energy Consumption (kWh per Hour)",
            range=c(0,1500)),
         legend= list(
           orientation="h"
         )
  )

plot

```


Weekend Average Trends
===================================== 

###
###
### Weekend Average Trends

Row {.tabset}
-----------------------------------------------------------------------

### May

```{r}

trace_1 <- round(generalLibrary$mean.weekend.may.1,1)
trace_2 <- round(generalLibrary$mean.weekend.may.2,1)
trace_3 <- round(generalLibrary$mean.weekend.may.3,1)
x <- generalLibrary$hr

plot<-plot_ly(x = ~x, y = ~trace_1, name = 'weekends 2014', type = 'scatter', mode = 'lines+markers') %>%
  add_trace(y = ~trace_2, name = 'weekends 2015', mode = 'lines+markers') %>%
  add_trace(y = ~trace_3, name = 'weekends 2016', mode = 'lines+markers')%>%
  layout(                       
         xaxis = list(           
            title = "Time (Hours)",      
            showgrid = F),       
         yaxis = list(           
            title = "Average Energy Consumption (kWh per Hour)",
            range=c(0,1500)),
         legend = list(
           orientation="h"
         )
  )

plot

```

### July

```{r}

trace_1 <- round(generalLibrary$mean.weekend.jul.1,1)
trace_2 <- round(generalLibrary$mean.weekend.jul.2,1)
trace_3 <- round(generalLibrary$mean.weekend.jul.3,1)
x <- generalLibrary$hr

plot<-plot_ly(x = ~x, y = ~trace_1, name = 'weekends 2014', type = 'scatter', mode = 'lines+markers') %>%
  add_trace(y = ~trace_2, name = 'weekends 2015', mode = 'lines+markers') %>%
  add_trace(y = ~trace_3, name = 'weekends 2016', mode = 'lines+markers')%>%
  layout(                       
         xaxis = list(           
            title = "Time (Hours)",      
            showgrid = F),       
         yaxis = list(           
            title = "Average Energy Consumption (kWh per Hour)",
            range=c(0,1500)),
         legend= list(
           orientation="h"
         )
  )

plot

```

### September

```{r}

trace_1 <- round(generalLibrary$mean.weekend.sep.1,1)
trace_2 <- round(generalLibrary$mean.weekend.sep.2,1)
trace_3 <- round(generalLibrary$mean.weekend.sep.3,1)
x <- generalLibrary$hr

plot<-plot_ly(x = ~x, y = ~trace_1, name = 'weekends 2014', type = 'scatter', mode = 'lines+markers') %>%
  add_trace(y = ~trace_2, name = 'weekends 2015', mode = 'lines+markers') %>%
  add_trace(y = ~trace_3, name = 'weekends 2016', mode = 'lines+markers')%>%
  layout(                       
         xaxis = list(           
            title = "Time (Hours)",      
            showgrid = F),       
         yaxis = list(           
            title = "Average Energy Consumption (kWh per Hour)",
            range=c(0,1500)),
         legend= list(
           orientation="h"
         )
  )

plot

```

### December

```{r}

trace_1 <- round(generalLibrary$mean.weekend.dec.1,1)
trace_2 <- round(generalLibrary$mean.weekend.dec.2,1)
trace_3 <- round(generalLibrary$mean.weekend.dec.3,1)
x <- generalLibrary$hr

plot<-plot_ly(x = ~x, y = ~trace_1, name = 'weekends 2014', type = 'scatter', mode = 'lines+markers') %>%
  add_trace(y = ~trace_2, name = 'weekends 2015', mode = 'lines+markers') %>%
  add_trace(y = ~trace_3, name = 'weekends 2016', mode = 'lines+markers')%>%
  layout(                       
         xaxis = list(           
            title = "Time (Hours)",      
            showgrid = F),       
         yaxis = list(           
            title = "Average Energy Consumption (kWh per Hour)",
            range=c(0,1500)),
         legend= list(
           orientation="h"
         )
  )

plot

```


Baseline Energy Consumption
=====================================

###
###
### Baseline Energy Consumption

Row 
-----------------------------------------------------------------------

### Chinese New Year

```{r}
begin="2016-02-06 00"
end="2016-02-14 23"

springbase=matrix(nrow=9,ncol=24,dimnames = list(as.character(generalLibrarybase$date[1:9])),c(1:24))
for(i in 1:24){
  springbase[,i]=generalLibrarybase[[i+1]][1:9]
}
springtime=timeBasedSeq(paste(begin,"/",end,sep=""),length=length(springbase))
spring=xts(c(t(springbase)),order.by=c(t(springtime)))

dygraph(spring,main="6 - 14 Feb 2016",xlab="Time",ylab="(kWh per Hour)")%>%
  dySeries(label = "Energy Consumption") 

```


Row 
-----------------------------------------------------------------------

### Final Exam Week

```{r}
begin="2014-01-13 00"
end="2014-01-17 23"

springbase=matrix(nrow=5,ncol=24,dimnames = list(as.character(generalLibrarybase$date[10:14])),c(1:24))
for(i in 1:24){
  springbase[,i]=generalLibrarybase[[i+1]][10:14]
}
springtime=timeBasedSeq(paste(begin,"/",end,sep=""),length=length(springbase))
spring=xts(c(t(springbase)),order.by=c(t(springtime)))

dygraph(spring,main="13 - 17 Jan 2014",xlab="Time",ylab="(kWh per Hour)")%>%
  dySeries(label = "Energy Consumption") 

```


Details on Selected Data
=====================================
###
###
### Details on Selected Data

Row 
-----------------------------------------------------------------------

### 

> 除春節和期末考週的時間序列外，本網站中都以各月份中連續4週週一到週日用電資料為逐時平均值的計算範圍；惟9月之資料是開學後一個月的資料。
> 底下說明各年、各月份選取資料的日期區間：

```{r fig.align='center'}

  df <- data.frame(
  Years = c(2014:2016),
  May = c("05/05-06/01","05/04-05/31","05/02-05/29"), 
  July = c("06/30-07/27","07/06-08/02","07/04-07/31"),
  September = c("09/15-10/12","09/14-10/11","09/12-10/09"),
  December = c("12/01-12/28","11/30-12/27","11/28-12/25"),
  stringsAsFactors = FALSE)

  kable(df,align='c')
  
```
